// GENERATED by tools/build-sw.mjs. Do not edit by hand; run `npm run build`.
const VERSION = '884c9871dbd2';
const CACHE = 'recomp-' + VERSION;
const ASSETS = [
  "./",
  "css/app.css",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg",
  "index.html",
  "js/core/dates.js",
  "js/core/foods.js",
  "js/core/format.js",
  "js/core/grocery.js",
  "js/core/ics.js",
  "js/core/macros.js",
  "js/core/plan.js",
  "js/core/prompts.js",
  "js/core/review.js",
  "js/core/scale.js",
  "js/core/schedule.js",
  "js/core/state.js",
  "js/core/stats.js",
  "js/core/storage.js",
  "js/core/store.js",
  "js/core/swap.js",
  "js/core/tdee.js",
  "js/data/builtin-foods.js",
  "js/data/example-plan.js",
  "js/main.js",
  "js/ui/components.js",
  "js/ui/ctx.js",
  "js/ui/dom.js",
  "js/ui/more.js",
  "js/ui/plan.js",
  "js/ui/progress.js",
  "js/ui/sheet-actions.js",
  "js/ui/sheets-food.js",
  "js/ui/sheets.js",
  "js/ui/today.js",
  "js/ui/train.js",
  "js/ui/welcome.js",
  "manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('recomp-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache first (the app is fully offline), network for anything we didn't precache.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try {
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch (err) {
        if (req.mode === 'navigate') {
          const shell = await cache.match('./');
          if (shell) return shell;
        }
        throw err;
      }
    })()
  );
});
