#!/usr/bin/env node
// Generates sw.js: the service worker that makes the app work offline.
//   node tools/build-sw.mjs           write sw.js
//   node tools/build-sw.mjs --check   exit 1 if sw.js is out of date
//
// Every shipped file is listed and hashed. When any file changes the hash
// changes, the browser installs the new worker, fetches everything into a fresh
// cache, and the app offers a reload. Run this (npm run build) after any change.

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative, sep, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const INCLUDE_DIRS = ['js', 'css', 'icons'];
const INCLUDE_FILES = ['index.html', 'manifest.webmanifest'];

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

export function listAssets() {
  const files = [...INCLUDE_FILES];
  for (const d of INCLUDE_DIRS) if (existsSync(join(root, d))) files.push(...walk(join(root, d)).map((f) => relative(root, f).split(sep).join('/')));
  return files.sort();
}

export function render() {
  const assets = listAssets();
  const h = createHash('sha256');
  for (const f of assets) {
    h.update(f);
    h.update(readFileSync(join(root, f)));
  }
  const version = h.digest('hex').slice(0, 12);
  return `// GENERATED by tools/build-sw.mjs. Do not edit by hand; run \`npm run build\`.
const VERSION = '${version}';
const CACHE = 'recomp-' + VERSION;
const ASSETS = ${JSON.stringify(['./', ...assets], null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('recomp-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache first (the app is fully offline), network for anything we didn't precache.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const hit = await cache.match(req, { ignoreSearch: true });
      if (hit) return hit;
      try {
        const res = await fetch(req);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch (err) {
        if (req.mode === 'navigate') {
          const shell = await cache.match('./');
          if (shell) return shell;
        }
        throw err;
      }
    })()
  );
});
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = render();
  const file = join(root, 'sw.js');
  if (process.argv.includes('--check')) {
    const cur = existsSync(file) ? readFileSync(file, 'utf8') : '';
    if (cur !== next) {
      console.error('sw.js is out of date. Run: npm run build');
      process.exit(1);
    }
    console.log('sw.js is up to date');
  } else {
    writeFileSync(file, next);
    console.log(`wrote sw.js (${listAssets().length} files)`);
  }
}
